FROM toozick/qcide-php-apache-base:v1

# Install composer packages
RUN mkdir -p /composer
WORKDIR /composer
COPY application/composer.json composer.json
RUN composer install
RUN chmod 777 vendor -R

WORKDIR /var/www/html/application
